Open the buffer without moving it
MagicDuck/grug-far.nvim pull request #102
Opened 2024-07-09 10:55 UTC by milksys

Using go to location moves the cursor to that location in that buffer.

Use open to navigate the buffer without moving it.

'o' key added

2024-07-10 17:49 UTC, MagicDuck commented
@milksys thanks for your contrib, I'll take a deeper look when I have some more time, but a couple of things I am slightly concerned about with the current impl are:
1. since we are using `gotoLocation()`, that could cause a cursor flicker as the cursor is moving between window. I think it might be preferable to open the buffer without moving the cursor, even if we end up duplicating some of the `gotoLocation` logic.
2. should not use `o` as the default keybind as that overrides "open line below" and grug-far is attempting as far as possible not to mess with any builtin vim keybinds. Maybe `<C-enter>` or `<localleader>o`?

2024-07-11 13:48 UTC, milksys commented
Thank you for your feedback

1. If the buffer exists, move to the buffer without opening the file, position the cursor, and then return.

2. I changed "c-enter" to "<localleader>o" in case it doesn't work on certain terminals.
However, I believe the "o" key is useful for navigation flow. Since the remapping structure is easy to adjust, I set the default value to "<localleader>o".

2024-07-11 18:14 UTC, MagicDuck requested changes
Looks great! Just a tiny change required.

2024-07-11 18:14 UTC, MagicDuck commented on lua/grug-far/actions/open.lua
> +  if bufnr == -1 then
this is nice!

I was hoping we would be able to open a file in the `prevWin` without moving windows/cursor, but it looks like there is no lua API for it, at least that I could find and `:edit` only works on current window. As such I am fine with the current solution 😄

2024-07-11 18:14 UTC, MagicDuck commented on lua/grug-far/farBuffer.lua
> +  utils.setBufKeymap(buf, 'Grug Far: open', keymaps.open, function()
nit: "open" -> "open location" (for consistency with "go to location")

2024-07-11 18:14 UTC, MagicDuck commented on lua/grug-far/opts.lua
> +  -- prevents excessive searching
thank you for fixing those typos

2024-07-11 18:14 UTC, MagicDuck commented on lua/grug-far/opts.lua
> +    open = { n = '<localleader>o' },
great!

2024-07-11 18:14 UTC, MagicDuck commented on tests/test_open.lua
> +T['can open a given location'] = function()
I wanted a test but felt like it might have been too much to request.
This is great! Thanks for exceeding expectations! 😆

2024-07-11 18:20 UTC, MagicDuck commented on lua/grug-far/render.lua
> +      { text = 'Open', keymap = keymaps.open },
could you bump up the value of `headerMaxWidth` in opts.lua, to maybe `110`?
With the additional action, the header wraps on 3 lines, which is a bit much:
<img width="838" alt="image" src="https://github.com/MagicDuck/grug-far.nvim/assets/95201/05602908-7d1f-4170-90b8-ade4d95a701a">

2024-07-12 00:58 UTC, milksys commented on lua/grug-far/render.lua
> +      { text = 'Open', keymap = keymaps.open },
<img width="1261" alt="image" src="https://github.com/user-attachments/assets/b045e66b-9725-467f-a76f-01499fda07f8">

Change it to 110 so it appears in two lines.

2024-07-12 16:42 UTC, MagicDuck approved these changes

2024-07-12 16:44 UTC, MagicDuck commented
@milksys Thanks for addressing the requested changes. All good from my side! I just notice there is a lint issue that needs fixing before we merge:
https://github.com/MagicDuck/grug-far.nvim/actions/runs/9900659009/job/27383384723?pr=102

2024-07-12 23:16 UTC, MagicDuck commented
FYI, I just merged an MR that contains an additional test (test_toggle_instance). You will need to rebase and update those snapshots as well. Sorry for the trouble!

2024-07-13 02:34 UTC, MagicDuck commented
@milksys looks good, unfortunately still has that lint issue: https://github.com/MagicDuck/grug-far.nvim/actions/runs/9916073251/job/27399161388?pr=102

2024-07-13 02:49 UTC, MagicDuck commented on lua/grug-far/actions/openLocation.lua
> +  local bufnr = vim.fn.bufnr(location.filename)
seems like lint is complaining about this?
You can try adding `---@diagnostic disable-next-line` above it if it gives you grief, I am guessing the type definition on it might not be smart enough to understand that bufnr() can take a string param

2024-07-13 02:50 UTC, MagicDuck commented on lua/grug-far/actions/openLocation.lua
> +  local bufnr = vim.fn.bufnr(location.filename)
actually, I'll just do it and fix it for you since it's easier for me to re-trigger the lint

2024-07-13 02:50 UTC, merged