feat: treesitter highlighting for search results
MagicDuck/grug-far.nvim pull request #115
Opened 2024-07-18 13:35 UTC by folke

I've been testing grug-far as a replacement for nvim-spectre and it looks great!

One thing I always missed in these types of plugins is treesitter highlighting of the search results.

Since I do something similar already in trouble.nvim, I figured to copy the relevant parts and integrate the technique in grug-far.

How it works?
- It determines the filetypes for the filenames of the results
- For each filetype, a treesitter parser is created with its `include_regions` set to the exact positions in the results buffer
- Then a special highlighter deals with the highlighting. It wraps highlighters for every filetype and renders it as one.

I'm still pretty new to grug-far, so I may have broken some things.

Let me know what you think!

![image](https://github.com/user-attachments/assets/035fd9b1-91af-4c03-a5f4-3570c2ae0606)

2024-07-18 22:52 UTC, MagicDuck requested changes
@folke Thanks for this amazing feature! I'd thought about it being a potentially cool idea before, but never knew enough about treesitter to implement something like this. Also, it's an honour to have you contribute to my plugin, I've learned a lot from your repos and use your plugins daily 😄 .

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/actions/search.lua
> +      resultsList.highlight(buf)
could we add an option to `opts.lua` to enable/disable highlighting? In general I think this is really nice to have, but am guessing there are situations in larger repos when it could lead to performance issues. I'll check on my side how  speedy it is to see if we should be defaulting with it off, but in any case it's good to able to turn it off.

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/resultsList.lua
> +M.regions = {}
there can be multiple grug-far instances, so what I've done so far is to put all state into `GrugFarContext`, one of which is created for each instance and cleaned up on close. So maybe move it to `context.state.highlightRegions`?

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/resultsList.lua
> +      state.resultsLastFileType = vim.filetype.match({ filename = state.resultsLastFilename })
note: this should also be conditional with highlight opt enabled.

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/resultsList.lua
> +  if context.state.resultsLastFileType then
I am guessing this logic should not happen for call on line 89, as that sets the mark for the file path heading. Nor should it happen for the calls in `markUnsyncedLines()`. 
Might be good to just extract this logic to a separate function and call it on line 97 (I think that's the only one you need to update regions, if I am reading it correctly).

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/resultsList.lua
> +    local text = vim.api.nvim_buf_get_lines(buf, line, line + 1, false)[1]
you can use `lastLocation.text`

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/resultsList.lua
> +  treesitter.attach(buf, {})
note: this should also be conditional with highlight opt enabled.

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/actions/search.lua
> +      resultsList.highlight(buf)
If treesitter can be attached to regions incrementally, this call could be at end of `appendResultsChunk()` instead. Am not familiar with that API though

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/treesitter.lua
> +local ns = vim.api.nvim_create_namespace('grug.treesitter')
since there can be multiple grug-far instances, this can be an anonymous namespace created in `createContext()` (grug-far.lua), similar to `locationsNamespace`

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/treesitter.lua
> +M.cache = {} ---@type table<number, table<string,{parser: vim.treesitter.LanguageTree, highlighter:vim.treesitter.highlighter, enabled:boolean}>>
due to multiple instances, ideally should go into grug-far.lua , `createContext()`, so it would be accessed like `context.state.treesitterCache` or somesuch.

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/treesitter.lua
> +M.did_setup = false
similar comment regarding state (`context.state.<some_good_name>`) 😄

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/treesitter.lua
> +    group = vim.api.nvim_create_augroup('grug.treesitter.hl', { clear = true }),
you can use `context.augroup` as that gets cleaned up properly when instance is closed. 
But actually this autocmd is not necessary if the cache is added to the `context.state`. There's also a `cleanup()` function in `setupCleanup()` in `grug-far.lua` if you need it for any additional things.

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/treesitter.lua
> +function M._attach_lang(buf, lang, regions)
missing @param for regions

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/treesitter.lua
> +        TSHighlighter.active[buf] = hl.highlighter
does this create global state that needs cleanup?

2024-07-18 22:52 UTC, MagicDuck commented on lua/grug-far/render/resultsList.lua
> +  local regions = vim.deepcopy(M.regions)
is this deepcopy necessary?

2024-07-18 22:54 UTC, MagicDuck commented
Tests passed so fairly confident nothing major broke! Just looks like there are a few small lint issues.

2024-07-18 22:56 UTC, MagicDuck commented on lua/grug-far/render/resultsList.lua
> +function M.highlight(buf)
missing @param

2024-07-18 23:10 UTC, MagicDuck commented
hmm, just did a quick test, not sure if I am doing something wrong, but for a .tsx file at least, the highlighting does not seem to be quite the same:
<img width="2235" alt="image" src="https://github.com/user-attachments/assets/4ea92938-4f2b-4835-a29d-eb596b9cd09a">

2024-07-18 23:16 UTC, MagicDuck commented on lua/grug-far/actions/search.lua
> +      resultsList.highlight(buf)
so just tested it locally and there appears to be a long delay at the end when treesitter does it's thing when there are a lot of results. Hence, I guess we either figure out how to do it incremental in which case we could consider it being default ON, or we have it default OFF.
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/ebde1d54-f624-4ef0-9714-ce5b02f1783a">

2024-07-19 00:34 UTC, MagicDuck commented on lua/grug-far/actions/search.lua
> +      resultsList.highlight(buf)
another thing I noticed, with treesitter on and lots of results (28000 lines in buffer), editing results text is laggy...

2024-07-19 04:01 UTC, MagicDuck commented on lua/grug-far/render/resultsList.lua
> +  if context.state.resultsLastFileType then
also, `context.state.resultsLastFileType` might be unnecessary, since you can just use `lastLocation.filename` to get the filetype, ex: vim.filetype.match({ filename = lastLocation.filename })

2024-07-19 04:01 UTC, MagicDuck commented on lua/grug-far/render/resultsList.lua
> +      state.resultsLastFileType = vim.filetype.match({ filename = state.resultsLastFilename })
this line might become unnecessary due to https://github.com/MagicDuck/grug-far.nvim/pull/115/files#r1683752787

2024-07-19 06:45 UTC, folke commented
Right, yes for tsx that's actually a known issue with Neovim's filetype detect.
See also here: https://github.com/echasnovski/mini.nvim/issues/1007#issuecomment-2206873360

I'll add a work-around for it.

As for the other comments, I'll look into it later today. Thank you for the review!

Btw, the grug with visual doesn't work properly right now when visual mode is still active.
To make it work properly the below needs to be added before getting the selection:

```lua
local is_visual = vim.fn.mode():lower():find("v")
if is_visual then -- needed to make visual selection work
  vim.cmd([[normal! v]])
end
```

Ok to add it to this PR as well?

There's also an issue with multiple far instances being created that sometimes get the same name and fail.
I'd like to fix that as well.

2024-07-19 09:04 UTC, folke commented on lua/grug-far/actions/search.lua
> +      resultsList.highlight(buf)
Added to `opts.lua` and fixed the performance issue.
Parsing is now incremental and realtime as part of `appendResultsChunk`.
Do let me know if you'd still see performance issues with getting results or editing results.

2024-07-19 09:04 UTC, folke commented on lua/grug-far/render/resultsList.lua
> +      state.resultsLastFileType = vim.filetype.match({ filename = state.resultsLastFilename })
done

2024-07-19 09:04 UTC, folke commented on lua/grug-far/render/resultsList.lua
> +M.regions = {}
done

2024-07-19 09:04 UTC, folke commented on lua/grug-far/render/resultsList.lua
> +  if context.state.resultsLastFileType then
fixed

2024-07-19 09:05 UTC, folke commented on lua/grug-far/render/treesitter.lua
> +local ns = vim.api.nvim_create_namespace('grug.treesitter')
That's not needed. There should ever only be one decoration provider for `grug-far`. 
It will work correctly for multiple instances.

2024-07-19 09:06 UTC, folke commented on lua/grug-far/render/treesitter.lua
> +M.cache = {} ---@type table<number, table<string,{parser: vim.treesitter.LanguageTree, highlighter:vim.treesitter.highlighter, enabled:boolean}>>
Better to keep it there, since there is always just one decoration provider that does the highlighting.

2024-07-19 09:07 UTC, folke commented on lua/grug-far/render/treesitter.lua
> +    group = vim.api.nvim_create_augroup('grug.treesitter.hl', { clear = true }),
Added a call to treesitter.clear

2024-07-19 09:07 UTC, folke commented on lua/grug-far/render/treesitter.lua
> +        TSHighlighter.active[buf] = hl.highlighter
I do an explicit destroy in treesitter.clear, but Neovim should also do cleanup on buf detach.

2024-07-19 09:08 UTC, folke commented on lua/grug-far/render/resultsList.lua
> +  local regions = vim.deepcopy(M.regions)
Yes, because the treesitter languagetree code changes the values from a Range4 to a Range6 and the second time you use the same regions, it does something weird and errors.

2024-07-19 09:08 UTC, folke commented
That `tsx` problem was also fixed.

2024-07-19 18:03 UTC, MagicDuck commented
> Ok to add it to this PR as well?
Ideally we would have another PR, but to be honest I am fine with whatever's easiest for you! Just happy to get the fixes 😄

2024-07-19 18:09 UTC, MagicDuck commented
Btw, just something that popped into my mind, can be another PR, but I think we need to make sure we also highlight the context if one `--context <num>`, `--after-context <num>`, `--before-context <num>` flags is passed:
<img width="855" alt="image" src="https://github.com/user-attachments/assets/d17388d9-7d0c-4c76-b50f-fd9906f7b9fe">

2024-07-19 18:26 UTC, MagicDuck approved these changes
Looks good to me, apart from one minor little nit and linting stuff! 😄  Going to pull it in locally to check the perf

2024-07-19 18:26 UTC, MagicDuck commented on lua/grug-far/render/resultsList.lua
> +  ---@type { filename?: string, lnum?: integer, col?: integer, text?: string, end_col?: integer, ft?: string }?
could use `ResultLocation` type defined in `grug-far.lua`. I think you just need to add `ft?: string` to that one

2024-07-19 18:26 UTC, MagicDuck commented on lua/grug-far/render/treesitter.lua
> +        TSHighlighter.active[buf] = hl.highlighter
ah nice! I think this was a missing piece in understanding for me!

2024-07-19 18:37 UTC, MagicDuck commented
Checked it locally. It's a speedy boy now 😄

2024-07-19 18:41 UTC, MagicDuck commented on lua/grug-far/render/resultsList.lua
> +  local from = (text or ''):match('^(%d+:%d+:)')
maybe just updating this would fix `--context <num>` highlighting?

2024-07-19 21:16 UTC, folke commented on lua/grug-far/render/resultsList.lua
> +  local from = (text or ''):match('^(%d+:%d+:)')
Will add this too. It's not just adding an extra region.
It's better to add the different lines in the same region since they belong together.
Will change!

2024-07-19 23:01 UTC, folke commented on lua/grug-far/render/resultsList.lua
> +  local from = (text or ''):match('^(%d+:%d+:)')
done

2024-07-19 23:02 UTC, folke commented
I've optimized the code for building consecutive regions (needed for `-A, -B, -C`).
I also optimized the `throttle` and `debounce` functions.

Highlighting now only incurs a small overhead. Profiled with perfanno.nvim.

2024-07-19 23:03 UTC, folke commented
But tests seems to fail now :)
I'm going to sleep here. Will check tomorrow.

2024-07-20 02:45 UTC, MagicDuck approved these changes

2024-07-20 07:03 UTC, folke commented
I've fixed the tests, but I don't really understand why that fixed it. Any ideas?
See my last commit.

2024-07-20 08:00 UTC, folke commented
fyi: I'm trying to fix that typecheck action.
That still uses neodev, which is deprecated and no longer needed with Neovim 0.10.0

However, I'm having a hard time making it all work :)

2024-07-20 09:17 UTC, folke commented
Finally! :)

2024-07-20 18:29 UTC, MagicDuck commented
> I've fixed the tests, but I don't really understand why that fixed it. Any ideas?
Hmm, that one's definitely a puzzler. I love the confidence that those headless neovim snapshot tests give, but sometimes I've also run into some weird behaviour in how / when they decide to render 😕 

> fyi: I'm trying to fix that typecheck action. That still uses neodev, which is deprecated and no longer needed with Neovim 0.10.0
Sorry for the trouble with the lint action! I copy-pasted that from somewhere pre 0.10.0 and did not realize it needed updating after 0.10.0 dropped. Thank you for heroically fixing it! 😄

2024-07-20 18:31 UTC, folke commented
That test failed for good reason I found eventually.
Reason was `getFileType` returning `nil` for some of the test buffers and the code didn't handle that well. But fixed that.

2024-07-20 18:32 UTC, MagicDuck commented
ah, good thing then!

2024-07-20 18:32 UTC, MagicDuck commented
kk, I am going to merge it. This is going to be a-m-a-z-i-n-g! 😄 
Thanks for all your hard work!

2024-07-20 18:32 UTC, merged

2024-07-20 18:34 UTC, folke commented
Awesome, thanks for merging!