feat: add previewLocation actions
MagicDuck/grug-far.nvim pull request #239
Opened 2024-09-03 01:40 UTC by leisiji

Add new feature: previewing location in a floating window.
![2024-09-03_09-29](https://github.com/user-attachments/assets/86a3e329-6915-4499-8f9c-8be800b6f8cd)

2024-09-03 21:41 UTC, MagicDuck requested changes
@leisiji Thanks for your contribution! 😄  Looks good apart from some minor things. Also, please add a test for this action.
See: https://github.com/MagicDuck/grug-far.nvim/blob/main/CONTRIBUTING.md#testing
and example for goto action here: https://github.com/MagicDuck/grug-far.nvim/blob/fe915b27cd19212f086e53ee5f2a480cf0d0a7e6/tests/base/test_goto.lua#L18

2024-09-03 21:41 UTC, MagicDuck commented on lua/grug-far/actions/previewLocation.lua
> +  local api = vim.api
just a style thing, I prefer to just use those directly like `vim.api.nvim_win_set_cursor` and `vim.fn.bufwinid` since it's apparent immediately that these are vim api and sometimes I copy lines to execute on the fly with `:lua ...`

2024-09-03 21:41 UTC, MagicDuck commented on lua/grug-far/opts.lua
> +---@field previewLocation KeymapDef
also add this in KeymapsOverride below.

2024-09-05 01:23 UTC, leisiji commented
I have fixed the above and added a test for previewLocation action.

2024-09-05 02:55 UTC, MagicDuck requested changes

2024-09-05 02:55 UTC, MagicDuck commented on tests/base/test_preview.lua
> +    windowCreationCommand = 'vsplit',
Do you need vsplit?

2024-09-05 02:55 UTC, MagicDuck commented on lua/grug-far/actions/previewLocation.lua
> +  local api = vim.api
This one did not get changed. Please humor me :)

2024-09-05 02:55 UTC, MagicDuck commented on lua/grug-far/opts.lua
> +---@field previewLocation KeymapDef
Need question mark after name cause its optional override.

2024-09-05 05:41 UTC, leisiji commented
All have been fixed.

2024-09-05 17:01 UTC, MagicDuck approved these changes

2024-09-05 17:01 UTC, MagicDuck commented
perfect, thank you! Looks good! 😄

2024-09-05 17:01 UTC, merged