Allow to customize options for floating windows
MagicDuck/grug-far.nvim pull request #300
Opened 2024-11-04 21:04 UTC by lervag

This is a first attempt at addressing https://github.com/MagicDuck/grug-far.nvim/issues/299; it is probably not perfect and may (will) need some work.

Let me know what you think!

2024-11-04 23:56 UTC, MagicDuck requested changes
@lervag Thank you for your contribution! 😄 
Please see my comments for some minor changes that should be done.

Ideally should also add some tests to `tests/base/test_ui.lua` where you override some option like the border and assert that the screenshot is correct. Tests use `mini.test`. Check out https://github.com/MagicDuck/grug-far.nvim/blob/main/CONTRIBUTING.md for how to run them via the command line.

2024-11-04 23:56 UTC, MagicDuck commented on lua/grug-far/opts.lua
> +  helpWinConfig = {
I think you can remove the `Config` suffix on those since it's understood as they are already in options.
so just `helpWindow`, `historyWindow`, ... would be sufficient

2024-11-04 23:56 UTC, MagicDuck commented on lua/grug-far/actions/help.lua
> +  }, opts.defaultOptions.helpWinConfig)
this will not allow users to override it. Please use `context.options.helpWinConfig` instead of `opts.defaultOptions.helpWinConfig`. Same for the other windows.

2024-11-04 23:59 UTC, MagicDuck commented on lua/grug-far/opts.lua
> +  -- options for help window
should add a bit more detail here. Like for example:
```
-- these are the same options as the ones that get passed to `vim.api.nvim_open_win()`: border, style, etc.
-- see :h nvim_open_win for more
```

2024-11-05 22:00 UTC, lervag commented
> @lervag Thank you for your contribution! 😄 Please see my comments for some minor changes that should be done.

Thanks for the good and useful comments; I've updated the code accordingly. I believe it should be quite good now.

> Ideally should also add some tests to `tests/base/test_ui.lua` where you override some option like the border and assert that the screenshot is correct. Tests use `mini.test`. Check out https://github.com/MagicDuck/grug-far.nvim/blob/main/CONTRIBUTING.md for how to run them via the command line.

Ok, I'll look into this as well when I get the time; probably tomorrow or Thursday.

2024-11-06 17:22 UTC, MagicDuck commented
Looks good! That test you added would be sufficient for the help window case. If you can, add similar tests for the history and preview windows.

2024-11-06 17:22 UTC, MagicDuck approved these changes

2024-11-06 21:01 UTC, lervag commented
Ok, I've added additional tests now. Please check if the tests are up to your standards here - the test framework is unfamiliar to me, so I may have misunderstood something.

2024-11-07 00:10 UTC, MagicDuck approved these changes
looks good! Thanks for patiently implementing all my suggestions! :)

2024-11-07 00:10 UTC, merged